package io.github.zyrouge.symphony.services.groove

import androidx.compose.runtime.Immutable
import androidx.room.Entity

/**
 * MAZIKA: the kind of thing a queue was played *from*.
 *
 * "Recently played" is about sources, not tracks — you played an album, a playlist, an
 * artist — so the history records what was tapped rather than what came out of the
 * speakers. [SONG] is the fallback for a track played straight out of a flat list, where
 * there is no larger thing to point at.
 */
enum class PlayedItemType {
    SONG,
    ALBUM,
    ARTIST,
    ALBUM_ARTIST,
    PLAYLIST,
    GENRE,
    FOLDER,
}

/**
 * A thing that can be played, identified in a way that survives a library rescan.
 *
 * That last part decides every [id] here, and the app has been caught by it once already
 * with custom song covers:
 *
 *  - album ids are *derived* from the album name and its album artists
 *    (`AlbumRepository.getIdFromSong`), so they are stable;
 *  - artists, album artists and genres are identified by name, folders by path;
 *  - playlist ids are persisted;
 *  - **song ids are regenerated by the scanner** and the songs table lives in the cache
 *    database, so a song is identified by its **path**.
 */
@Immutable
data class PlaySource(val type: PlayedItemType, val id: String) {
    companion object {
        fun song(path: String) = PlaySource(PlayedItemType.SONG, path)
        fun album(albumId: String) = PlaySource(PlayedItemType.ALBUM, albumId)
        fun artist(name: String) = PlaySource(PlayedItemType.ARTIST, name)
        fun albumArtist(name: String) = PlaySource(PlayedItemType.ALBUM_ARTIST, name)
        fun playlist(playlistId: String) = PlaySource(PlayedItemType.PLAYLIST, playlistId)
        fun genre(name: String) = PlaySource(PlayedItemType.GENRE, name)
        fun folder(path: String) = PlaySource(PlayedItemType.FOLDER, path)
    }
}

/**
 * One row per item, holding only its most recent play — replaying something moves it to
 * the front of the list instead of adding a duplicate, and the table stays small.
 *
 * [type] is stored as the enum name rather than its ordinal so reordering the enum can
 * never silently reinterpret existing rows.
 */
@Immutable
@Entity("played_items", primaryKeys = ["type", "id"])
data class PlayedItem(
    val type: String,
    val id: String,
    val playedAt: Long,
) {
    fun toSource(): PlaySource? = PlayedItemType.entries
        .firstOrNull { it.name == type }
        ?.let { PlaySource(it, id) }

    companion object {
        fun of(source: PlaySource, playedAt: Long) =
            PlayedItem(source.type.name, source.id, playedAt)
    }
}
