package io.github.zyrouge.symphony.services.groove

import androidx.compose.runtime.Immutable
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * MAZIKA: a user-chosen cover for a single song.
 *
 * Keyed by the song's **path**, deliberately not its id: song ids are regenerated by
 * the scanner and the songs table lives in the cache database, so anything keyed by id
 * would be lost on the next rescan. The path is stable for as long as the file is.
 */
@Immutable
@Entity("song_covers")
data class SongCover(
    @PrimaryKey
    val path: String,
    val coverFile: String,
)
