#!/usr/bin/env node
/**
 * MAZIKA — "build-apk"
 *
 * Runs a clean debug build:  gradlew clean assembleDebug
 *
 * Handles the two things that otherwise make a fresh clone fail:
 *   1. The translation resources (app/src/main/assets/i18n + *.g.kt) are
 *      git-ignored and generated by phrasey. If they are missing we run
 *      `npm run prebuild` first.
 *   2. Gradle here expects a JDK 17+. We honour an existing JAVA_HOME, else we
 *      look for a suitable JDK in the usual install locations, else we fall back
 *      to whatever `java` is on PATH.
 *
 * Override the JDK explicitly with:  JAVA_HOME=/path/to/jdk npm run build-apk
 * Extra Gradle args are forwarded:   npm run build-apk -- --stacktrace
 */
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const projectRoot = resolve(dirname(process.argv[1] ?? "."), "..");
const isWindows = process.platform === "win32";
const gradlew = join(projectRoot, isWindows ? "gradlew.bat" : "gradlew");

/** @param {string} message @returns {never} */
function fail(message) {
    console.error(`\n[build-apk] ${message}\n`);
    process.exit(1);
}

/**
 * @param {string} command
 * @param {string[]} args
 * @param {import("node:child_process").SpawnSyncOptions} [options]
 */
function run(command, args, options = {}) {
    console.log(`[build-apk] > ${command} ${args.join(" ")}`);
    const result = spawnSync(command, args, {
        cwd: projectRoot,
        stdio: "inherit",
        shell: isWindows, // .bat/.cmd need a shell on Windows
        ...options,
    });
    if (result.error) {
        fail(`failed to start "${command}": ${result.error.message}`);
    }
    return result.status ?? 1;
}

/** Find a JDK >= 17: explicit JAVA_HOME wins, otherwise scan common locations. */
function resolveJavaHome() {
    if (process.env.JAVA_HOME && existsSync(process.env.JAVA_HOME)) {
        return process.env.JAVA_HOME;
    }
    const candidateRoots = isWindows
        ? [
              "C:\\Program Files\\Eclipse Adoptium",
              "C:\\Program Files\\Java",
              "C:\\Program Files\\Microsoft",
          ]
        : ["/usr/lib/jvm", "/Library/Java/JavaVirtualMachines"];
    for (const root of candidateRoots) {
        if (!existsSync(root)) continue;
        let entries;
        try {
            entries = readdirSync(root);
        } catch {
            continue;
        }
        // Prefer 17 (what this project builds with), then any newer LTS.
        const ranked = entries
            .map((name) => ({ name, version: Number((name.match(/(?:jdk-?|-)(\d{2})/) || [])[1]) }))
            .filter((x) => Number.isFinite(x.version) && x.version >= 17)
            .sort((a, b) => (a.version === 17 ? -1 : b.version === 17 ? 1 : a.version - b.version));
        for (const { name } of ranked) {
            const home = join(root, name);
            const javaBin = join(home, "bin", isWindows ? "java.exe" : "java");
            if (existsSync(javaBin)) return home;
            // macOS layout
            const nested = join(home, "Contents", "Home");
            if (existsSync(join(nested, "bin", "java"))) return nested;
        }
    }
    return null; // fall back to PATH
}

if (!existsSync(gradlew)) {
    fail(`Gradle wrapper not found at ${gradlew}`);
}

// 1. Generated translation resources (git-ignored) must exist before compiling.
if (!existsSync(join(projectRoot, "app", "src", "main", "assets", "i18n"))) {
    console.log("[build-apk] translation resources missing — running prebuild");
    const npm = isWindows ? "npm.cmd" : "npm";
    if (run(npm, ["run", "prebuild"]) !== 0) {
        fail("prebuild (i18n generation) failed");
    }
}

// 2. Pick a JDK.
const javaHome = resolveJavaHome();
const env = { ...process.env };
if (javaHome) {
    env.JAVA_HOME = javaHome;
    console.log(`[build-apk] JAVA_HOME=${javaHome}`);
} else {
    console.log("[build-apk] JAVA_HOME not resolved — using `java` from PATH (must be 17+)");
}

// 3. Clean debug build. Any extra CLI args are appended to the Gradle command.
const extraArgs = process.argv.slice(2);
const status = run(gradlew, ["clean", "assembleDebug", ...extraArgs], { env });

if (status === 0) {
    const outDir = join("app", "build", "outputs", "apk", "debug");
    console.log(
        [
            "",
            "[build-apk] BUILD SUCCESSFUL",
            `[build-apk] APKs: ${outDir}`,
            `[build-apk]   universal -> ${join(outDir, "app-universal-debug.apk")}`,
            "",
        ].join("\n"),
    );
} else {
    console.error(`\n[build-apk] BUILD FAILED (gradle exit code ${status})\n`);
}
process.exit(status);
